CREATE FUNCTION GET_PIVOT_HEADER
(@PREFIX NVARCHAR = NULL, @COLUMN_COUNT INT)
RETURNS NVARCHAR(MAX) AS
BEGIN
	---SELECT ',' + name FROM temp1 FOR XML PATH ('')
	DECLARE @COUNTER INT,@PIVOT_HEADER NVARCHAR(MAX)
  	SET @COUNTER = 1
	WHILE @COUNTER < = @COLUMN_COUNT
	BEGIN
    	IF @PIVOT_HEADER IS NULL
      	BEGIN
        	SET @PIVOT_HEADER = QUOTENAME(@COUNTER)
      	END
      	ELSE
      	BEGIN
        	SET @PIVOT_HEADER = @PIVOT_HEADER + ',' + QUOTENAME(@COUNTER)
      	END
		SET @COUNTER = @COUNTER +1
	END
	RETURN @PIVOT_HEADER
END