#1

Create Table Main(HeadColumn VARCHAR(100))
INSERT INTO MAIN VALUES('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H')


#2 RUN CREATE PROCEDURE.SQL FILE

#3 

DECLARE @USERINPUT INT
SET @USERINPUT = 2 --3,4,5,10,500,1000
EXECUTE UPDATE_REPORT @USERINPUT


---SUPPORTING DROPS IF NEEDED
DROP TABLE REPORT_TABLE
DROP PROCEDURE UPDATE_REPORT

----------------------------------------------


