CREATE PROCEDURE UPDATE_REPORT(
@USERINPUT INT) AS
BEGIN

IF @USERINPUT > 1024
BEGIN
	--RAISE ERRO
	PRINT 'PLEASE ENTER VALUE LESS THAN 1024'
END
ELSE
BEGIN
	DECLARE @count INT,@ColumnName as Nvarchar(MAX);
	Declare @sql NVarchar(MAX);
	SET @count = 1;
	set @columnname =''    
	WHILE @count<= @USERINPUT
	BEGIN
   
		set @columnname = @ColumnName +  'COLUMN' + CAST(@COUNT AS VARCHAR) + ' varchar(100)' + ',' 
		SET @count = @count + 1;
   
	END;
	SET @ColumnName = LEFT(@ColumnName,LEN(@ColumnName)-1)
	set @SQL = 'Create Table REPORT_TABLE (' + @ColumnName + ')'
	EXEC sp_executesql @SQL

	--TRAVERSE CURSOR TO FILL COLUMNS
-----------------------------------------------
SET @COUNT=1
SET @SQL =''
DECLARE @MAINVALUE VARCHAR(100);
DECLARE MYCURSOR CURSOR FOR 
SELECT * FROM MAIN
OPEN MYCURSOR
FETCH NEXT FROM MYCURSOR INTO @MAINVALUE
WHILE @@FETCH_STATUS = 0
BEGIN
    IF @COUNT = @USERINPUT
    BEGIN
		
		SET @SQL = 'INSERT INTO REPORT_TABLE VALUES (' + @SQL + QUOTENAME(@MAINVALUE,'''') +')'
		EXEC sp_executesql @SQL
		PRINT @SQL
		SET @SQL =''
		SET @COUNT = 1
    END
    ELSE
    BEGIN
    	SET @SQL = @SQL  + QUOTENAME(@MAINVALUE,'''') + ','
		SET @COUNT = @COUNT + 1
		
    END
    FETCH NEXT FROM MYCURSOR INTO @MAINVALUE
 END
CLOSE MYCURSOR
DEALLOCATE MYCURSOR

--LAST ROW MIGHT HAVING MISSING VALUES FOR COLUMNS PUT NULL VALUES
WHILE @COUNT <= @USERINPUT
BEGIN

	SET @SQL = @SQL  + ''''','
	SET @COUNT = @COUNT + 1
	

	IF @COUNT > @USERINPUT
	BEGIN
		
		SET @SQL = LEFT(@SQL,LEN(@SQL)-1)
		SET @SQL = 'INSERT INTO REPORT_TABLE VALUES (' + @SQL +')'
		PRINT @SQL
		EXEC sp_executesql @SQL
	END
	
	
	--DROP TABLE REPORT_TABLE
	
END
SELECT * FROM REPORT_TABLE	
DROP TABLE REPORT_TABLE
END
END
