CREATE PROCEDURE UPDATE_REPORT(
@USERINPUT INT) AS
BEGIN

	DECLARE @COLUMN_COUNT NVARCHAR(MAX),@PIVOT_HEADER NVARCHAR(MAX),@SQL NVARCHAR(MAX)
	SET @PIVOT_HEADER = DBO.GET_PIVOT_HEADER(NULL,@USERINPUT);
	SET @COLUMN_COUNT = @USERINPUT;
    
  SET @SQL = '
   WITH CTE AS
  (
      SELECT 
          ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) ROWNO,
          headcolumn
      FROM Main
  )
      SELECT * FROM (      
      SELECT 
          IIF(CA.COLUMNNO =0,CA.ROWNO-1 ,CA.ROWNO) SNO,
          IIF(CA.COLUMNNO =0,'+ @COLUMN_COUNT +',CA.COLUMNNO) COLUMNNO,
          headcolumn
      FROM CTE
      CROSS APPLY 
      (SELECT
          CTE.ROWNO / '+ @COLUMN_COUNT +' ROWNO, 	  --DIVIDE ROW_NUMBER BY COLUMN COUNT 
          CTE.ROWNO % '+ @COLUMN_COUNT +' COLUMNNO  --MODOLO TO GET COLUMNNO / TO TRANSPOSE AS COLUMN 
       ) AS CA) AS X 
       PIVOT
       (
         MAX(headcolumn) FOR 
         COLUMNNO IN  ('+ @PIVOT_HEADER + ')
        ) AS Y;'
     
 	EXECUTE SP_EXECUTESQL @SQL
END