CREATE PROCEDURE UPDATE_REPORT4(
@COLUMN_COUNT INT) AS
BEGIN

	DECLARE @PIVOT_HEADERS NVARCHAR(MAX);

	SELECT  @PIVOT_HEADERS = (
	SELECT TOP (SELECT @COLUMN_COUNT) 
	',' + 'Column' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS NVARCHAR) FROM MAIN FOR XML PATH ('')  
	);
	SET @PIVOT_HEADERS = STUFF(@PIVOT_HEADERS,1,1,'');
	PRINT @PIVOT_HEADERS;
--

	DECLARE @sColumn_Count NVARCHAR(MAX) = @COLUMN_COUNT,@SQL NVARCHAR(MAX);

	SET @SQL = '
	;WITH CTE AS (
	SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ROWNO,HEADCOLUMN FROM MAIN)
	SELECT 
	*FROM (
	SELECT
		ROW_NUMBER() OVER (PARTITION BY CTE.ROWNO % '+@sColumn_Count +' ORDER BY (CTE.ROWNO)) AS SNO,
		''Column'' + CAST(
		ROW_NUMBER() OVER (PARTITION BY (IIF(CTE.ROWNO% '+@sColumn_Count +' = 0,CTE.ROWNO-1,CTE.ROWNO) /'+@sColumn_Count +') ORDER BY (CTE.ROWNO)) 
		AS VARCHAR)
		AS COLUMNNO,
		HEADCOLUMN FROM CTE 
		) AS P
	PIVOT
	(
		MAX(HeadColumn) FOR ColumnNo in (' + @PIVOT_HEADERS + ')
	)AS X'
	
	EXECUTE SP_EXECUTESQL @SQL
END
